FROM python:3.11-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY pyproject.toml ./

ENV CELERY_APP=app.workers.celery_app.celery_app
CMD ["celery", "-A", "app.workers.celery_app.celery_app", "worker", "-l", "INFO", "-c", "12", "--prefetch-multiplier=1"]
